### ISSUE TITLE
Any reference？

### ISSUE THREAD

**Issue by eleboss** [AMatusV/qrotor-bstep#1]
Hi,
I am currently learning backstepping control, any good suggestion of reference meterial? 

BTW, could you provide some reference of you code?

Best,
Lin.

**Comment by AMatusV** [comment]
Hello,

I think you should check the work of the developer of the backstepping method, in particular:

Petar V. Kokotovich, "The Joy of Feedback: Nonlinear and Adaptive," IEEE Control Systems Magazine, 1992.

The reference of the code is:

Antonio Matus-Vargas, et al., "Parametric Optimization for Nonlinear Quadcopter Control using Stochastic Test Signals," Robot Operating System (ROS), Springer, 2020.

Cheers,
AMV

**Comment by eleboss** [comment]
Many thanks!
